os: Visual Studio 2015

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "13"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --build-from-source --verbose
  - .\node_modules\.bin\node-pre-gyp.cmd package --runtime=$npm_config_runtime --target=$npm_config_target
  - .\node_modules\.bin\node-pre-gyp.cmd publish --runtime=$npm_config_runtime --target=$npm_config_target

build: OFF
test: OFF
deploy: OFF
