os: Visual Studio 2015

install:
  - ps: Install-Product node $env:NODE_VERSION $env:PLATFORM
  - npm install --build-from-source --verbose
  - .\node_modules\.bin\node-pre-gyp.cmd package --runtime=$npm_config_runtime --target=$npm_config_target
  - .\node_modules\.bin\node-pre-gyp.cmd publish --runtime=$npm_config_runtime --target=$npm_config_target

build: OFF
test: OFF
deploy: OFF
