# Golang CircleCI 2.0 configuration file
version: 2

executors:
  my-executor:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/reaandrew/surge

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: go get -u github.com/tcnksm/ghr
      - run: go get github.com/Songmu/goxz/cmd/goxz
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: GOOS=windows go get -u github.com/spf13/cobra
      - run: goxz -d out
      - persist_to_workspace:
          root: out
  publish:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /go/src/github.com/reaandrew/surge
      - run: ghr -n "latest" "$CIRCLE_TAG" out

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
      - publish:
          filters:
            tags:
              only: /v[\d\.]+/
          
