# Golang CircleCI 2.0 configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/reaandrew/surge
    steps:
      - checkout
      - run: go get github.com/Songmu/goxz/cmd/goxz
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: GOOS=windows go get -u github.com/spf13/cobra
      - run: goxz -d out
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/reaandrew/surge
    steps:
      - attach_workspace:
          at: /go/src/github.com/reaandrew/surge/out
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -u reaandrew -r surge -n "latest" "$CIRCLE_TAG" out
workflows:
  version: 2.1
  main:
    jobs:
      - build:
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /[^-]+/
          
